### ISSUE TITLE
How to Repackage Phantom 3 advanced Firmware

### ISSUE THREAD

**Issue by jh1113** [o-gs/dji-firmware-tools#283]
I want to modify the firmware and re-compress it

![image](https://user-images.githubusercontent.com/62418986/177907712-14c99c30-34a7-49a9-be79-5a2a98371ead.png)

![image](https://user-images.githubusercontent.com/62418986/177907658-d586292a-328c-42aa-b61c-ddfbbe28f9a2.png)
Modifying a file (Shadow)

Finally, I want to compress the file again

Please teach me the way. Help me, please.

**Comment by mefistotelis** [comment]
Just make sure to mount the rootfs image and modify there instead of extracting.
Besides that, there are no caveats - just use the scripts in reverse order with proper parameters to get back to one binary.

Non-signed firmwares (before Mavic) can be repackaged without additional knowledge.

Here's a simple test which does the first level:
https://github.com/o-gs/dji-firmware-tools/blob/master/tests/test_dji_xv4_fwcon_rebin1.sh

For details on the modules inside - use the project wiki.
