### ISSUE TITLE
What happens if you only update the drone firmware

### ISSUE THREAD

**Issue by The11thPlague** [o-gs/dji-firmware-tools#378]
I have a Mavic Air 2S produced in March 2021, with stock firmware (no changes).
I'd like to update the firmware to a newer official version, but not to the latest version.

On DDD I can only find drone (aircraft) firmware versions, but nothing for the RC-N1 controller (remote).
If I only update the drone (aircraft) firmware but keep the controller on the old firmware, will they still work fine together?

What about battery firmware?

**Comment by mefistotelis** [comment]
In most cases updating FW on only one side will cause no issues. This is because updates are introducing various changes, not always AC-RC protocol changes. But sometimes it does happen that DJI changes something in the protocol, which makes the AC and RC firmware no longer compatible.

So, it will probably work, but it might not. Check on forums designated for specific drone models, and look into release notes - that might give you some specifics.

The answer for battery FW is almost identical - it also uses a protocol to talk to the drone.
